In [1]:
import pandas as pd

In [2]:
sql = pd.read_csv(r'C:\Users\Admin\sql\dataset_1_202609160857.csv')

In [3]:
sql

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680
12680,Work,Alone,Rainy,55,7AM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12681
12681,Work,Alone,Snowy,30,7AM,Coffee House,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12682
12682,Work,Alone,Snowy,30,7AM,Bar,1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,0,12683
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

In [4]:
sql[['weather','temperature']]

      weather  temperature
0       Sunny           55
1       Sunny           80
2       Sunny           80
3       Sunny           80
4       Sunny           80
...       ...          ...
12679   Rainy           55
12680   Rainy           55
12681   Snowy           30
12682   Snowy           30
12683   Sunny           80

[12684 rows x 2 columns]

In [5]:
sql.head(10)

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
5,No Urgent Place,Friend(s),Sunny,80,6PM,Restaurant(<20),2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,6
6,No Urgent Place,Friend(s),Sunny,55,2PM,Carry out & Take away,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,7
7,No Urgent Place,Kid(s),Sunny,80,10AM,Restaurant(<20),2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,8
8,No Urgent Place,Kid(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,9
9,No Urgent Place,Kid(s),Sunny,80,10AM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,10

In [6]:
sql['passanger'].unique()

<ArrowStringArray>
['Alone', 'Friend(s)', 'Kid(s)', 'Partner']
Length: 4, dtype: str

In [7]:
sql[sql['destination']=='Home']

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
13,Home,Alone,Sunny,55,6PM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,1,0,1,14
14,Home,Alone,Sunny,55,6PM,Restaurant(20-50),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,15
15,Home,Alone,Sunny,80,6PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,16
35,Home,Alone,Sunny,55,6PM,Bar,1d,Male,21,Single,...,4~8,4~8,less1,1,0,0,1,0,1,36
36,Home,Alone,Sunny,55,6PM,Restaurant(20-50),1d,Male,21,Single,...,4~8,4~8,less1,1,1,0,0,1,0,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12675,Home,Alone,Snowy,30,10PM,Coffee House,2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,0,1,0,12676
12676,Home,Alone,Sunny,80,6PM,Restaurant(20-50),1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12677
12677,Home,Partner,Sunny,30,6PM,Restaurant(<20),1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,1,12678
12678,Home,Partner,Sunny,30,10PM,Restaurant(<20),2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,1,0,0,12679
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680

In [8]:
sql.sort_values('coupon')

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
9,No Urgent Place,Kid(s),Sunny,80,10AM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,10
13,Home,Alone,Sunny,55,6PM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,1,0,1,14
17,Work,Alone,Sunny,55,7AM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,1,0,1,0,18
24,No Urgent Place,Friend(s),Sunny,80,10AM,Bar,1d,Male,21,Single,...,4~8,4~8,less1,1,0,0,0,1,1,25
35,Home,Alone,Sunny,55,6PM,Bar,1d,Male,21,Single,...,4~8,4~8,less1,1,0,0,1,0,1,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12666,No Urgent Place,Friend(s),Snowy,30,2PM,Restaurant(<20),1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12667
12668,No Urgent Place,Alone,Sunny,80,10AM,Restaurant(<20),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12669
12671,No Urgent Place,Partner,Snowy,30,10AM,Restaurant(<20),1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12672
12677,Home,Partner,Sunny,30,6PM,Restaurant(<20),1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,1,12678
12678,Home,Partner,Sunny,30,10PM,Restaurant(<20),2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,1,0,0,12679

In [9]:
sql.rename(columns={'destination':'Destination'},inplace= True)

In [10]:
sql

,Destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680
12680,Work,Alone,Rainy,55,7AM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12681
12681,Work,Alone,Snowy,30,7AM,Coffee House,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12682
12682,Work,Alone,Snowy,30,7AM,Bar,1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,0,12683
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

In [11]:
sql.groupby('occupation').size().to_frame('Count').reset_index()

                                   occupation  Count
0                  Architecture & Engineering    175
1    Arts Design Entertainment Sports & Media    629
2   Building & Grounds Cleaning & Maintenance     44
3                        Business & Financial    544
4                 Community & Social Services    241
5                     Computer & Mathematical   1408
6                   Construction & Extraction    154
7                  Education&Training&Library    943
8                  Farming Fishing & Forestry     43
9          Food Preparation & Serving Related    298
10       Healthcare Practitioners & Technical    244
11                         Healthcare Support    242
12          Installation Maintenance & Repair    133
13                                      Legal    219
14               Life Physical Social Science    170
15                                 Management    838
16            Office & Administrative Support    639
17                    Personal Care & Service    175
18                     Production Occupations    110
19                         Protective Service    175
20                                    Retired    495
21                            Sales & Related   1093
22                                    Student   1584
23           Transportation & Material Moving    218
24                                 Unemployed   1870

In [12]:
sql.groupby('weather')['temperature'].mean().to_frame('avg_temp').reset_index()

  weather   avg_temp
0   Rainy  55.000000
1   Snowy  30.000000
2   Sunny  68.946271

In [13]:
sql.groupby('weather')['temperature'].size().to_frame('Count_temp').reset_index()

  weather  Count_temp
0   Rainy        1210
1   Snowy        1405
2   Sunny       10069

In [14]:
sql.groupby('weather')['temperature'].nunique().to_frame('count_distinct_temp').reset_index()

  weather  count_distinct_temp
0   Rainy                    1
1   Snowy                    1
2   Sunny                    3

In [15]:
sql.groupby('weather')['temperature'].sum().to_frame('sum_temp').reset_index()

  weather  sum_temp
0   Rainy     66550
1   Snowy     42150
2   Sunny    694220

In [16]:
sql.groupby('weather')['temperature'].min().to_frame('min_temp').reset_index()

  weather  min_temp
0   Rainy        55
1   Snowy        30
2   Sunny        30

In [17]:
sql.groupby('weather')['temperature'].max().to_frame('min_temp').reset_index()

  weather  min_temp
0   Rainy        55
1   Snowy        30
2   Sunny        80

In [18]:
sql.groupby('occupation').filter(lambda x: x['occupation'].iloc[0] == 
'Student').groupby('occupation').size()

occupation
Student    1584
dtype: int64

In [24]:
sql_u= pd.read_csv(r'C:\Users\Admin\sql\table_to_union_202609161531.csv')

In [20]:
sql_u

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,UNION,UNION,UNION,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1

In [26]:
sql_j = pd.read_csv(r'C:\Users\Admin\sql\table_to_join_202609161558.csv')

In [27]:
sql_j

   time part_of_day
0   2PM   Afternoon
1  10AM     Morning
2   6PM     Evening
3   7AM     Morning
4  10PM       Night

In [28]:
pd.concat([sql_u, sql_j])['destination'].drop_duplicates()

0    UNION
0      NaN
Name: destination, dtype: str

In [29]:
pd.merge(sql_u, sql_j[['time', 'part_of_day']], on='time', how='inner')[['destination', 'time', 'part_of_day']]

  destination time part_of_day
0       UNION  2PM   Afternoon

In [31]:
sql_u[sql_u['passanger'] == 'Alone'][['destination', 'passanger']]

Empty DataFrame
Columns: [destination, passanger]
Index: []

In [32]:
sql[sql['weather'].str.startswith('Sun')]

,Destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12673,Home,Alone,Sunny,30,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,0,12674
12676,Home,Alone,Sunny,80,6PM,Restaurant(20-50),1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12677
12677,Home,Partner,Sunny,30,6PM,Restaurant(<20),1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,1,12678
12678,Home,Partner,Sunny,30,10PM,Restaurant(<20),2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,1,0,0,12679
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

In [34]:
sql[(sql['temperature'] >= 29) & (sql['temperature'] <= 75)]['temperature'].unique()

array([55, 30])